#!/bin/sh

# remove files from server location
sudo rm -R /Library/WebServer/Documents/

# uninstall apache setup files
sudo mv /private/etc/apache2/httpd.conf.oslbackup /private/etc/apache2/httpd.conf

# uninstall JSON services
sudo pear uninstall Services_JSON-1.0.1

# uninstall php setup files
sudo mv /private/etc/php.ini.oslbackup /private/etc/php.ini

# restart apache
sudo /usr/sbin/apachectl restart

# delete databases on CouchDBX, requires CouchDBX to be installed and running!
curl -X DELETE http://localhost:5984/user
curl -X DELETE http://localhost:5984/feedback
curl -X DELETE http://localhost:5984/resourcebundle