require 'rubygems'
require 'objective-j'
require 'objective-j/bundletask'

if !ENV['CONFIG']
    ENV['CONFIG'] = 'Debug'
end

ObjectiveJ::BundleTask.new(:ProjectOSL) do |t|
    t.name          = 'Project OSL'
    t.identifier    = 'com.yourcompany.ProjectOSL'
    t.version       = '1.0'
    t.author        = 'Your Company'
    t.email         = 'feedback @nospam@ yourcompany.com'
    t.summary       = 'Project OSL'
    t.sources       = FileList['*.j']
    t.resources     = FileList['Resources/*']
    t.index_file    = 'index.html'
    t.info_plist    = 'Info.plist'
    t.build_path    = File.join('Build', ENV['CONFIG'], 'ProjectOSL')
    t.flag          = '-DDEBUG' if ENV['CONFIG'] == 'Debug'
    t.flag          = '-O' if ENV['CONFIG'] == 'Release'
end

task :default => [:ProjectOSL]

desc "This task runs the script to update the test server to the latest git repo."
task :deploy_test do
	system("../utilities/server/Test_Server/update_test_server.sh")
end

desc "This task runs the script to update the production server with the latest release cycle using the files on the test server."
task :deploy_production do
	system("../utilities/server/Production_Server/push_to_production_server.sh")
end

task :test do
    system("objj RunTests.j")
end
